# Generated by Django 4.0.6 on 2022-07-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип связи')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Инф. система')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Короткое наименование')),
                ('fullname', models.TextField(verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=13, null=True, verbose_name='ИНН')),
                ('on_contract', models.BooleanField(verbose_name='контракт заключен')),
            ],
        ),
        migrations.CreateModel(
            name='TStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус задачи')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Username')),
                ('user_uid', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now_add=True)),
                ('dt_plan', models.DateField(verbose_name='Дата повторной связи')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('help_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.helptype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.tstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Проблема')),
                ('infosys', models.ManyToManyField(to='helpdesk.infosys')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('sec_name', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('anydesk_id', models.CharField(max_length=50, verbose_name='ID AnyDesk')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.org')),
                ('user_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.appointment')),
            ],
        ),
    ]
