# Generated by Django 4.0.6 on 2022-07-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='infosys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.infosys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='org_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.orguser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infosys',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='org',
            name='fullname',
            field=models.TextField(null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='org',
            name='on_contract',
            field=models.BooleanField(default=True, verbose_name='контракт заключен'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='anydesk_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ID AnyDesk'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='user_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.appointment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dt_plan',
            field=models.DateField(null=True, verbose_name='Дата повторной связи'),
        ),
    ]
