# Generated by Django 4.0.6 on 2022-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_ticket_infosys_ticket_org_ticket_org_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosys',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
