# Generated by Django 4.0.6 on 2022-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_infosys_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='fullname',
            field=models.TextField(blank=True, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='org',
            name='inn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID AnyDesk'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='sec_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
