# Generated by Django 4.0.6 on 2022-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_org_fullname_alter_org_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
    ]
