# Generated by Django 4.0.6 on 2022-07-12 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_alter_ticket_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
