# Generated by Django 4.0.6 on 2022-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_ticket_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='org',
        ),
    ]
