# Generated by Django 4.0.6 on 2022-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_remove_ticket_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dt_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Дата повторной связи'),
        ),
    ]
