# Generated by Django 4.0.6 on 2022-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_alter_ticket_dt_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
    ]
