# Generated by Django 4.0.6 on 2022-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='phone',
            field=models.JSONField(null=True, verbose_name='Телефоны'),
        ),
    ]
