# Generated by Django 4.0.6 on 2022-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_alter_orguser_phone_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефоны'),
        ),
    ]
