# Generated by Django 4.0.6 on 2022-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_phonenumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
