# Generated by Django 4.0.6 on 2022-08-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_orguser_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='helptype',
            options={'verbose_name': 'Тип поддержки', 'verbose_name_plural': 'Типы поддержки'},
        ),
        migrations.AlterModelOptions(
            name='infosys',
            options={'verbose_name': 'ИС', 'verbose_name_plural': 'ИС'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='orguser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Список проблем'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='tstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='orguser',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.org', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='user_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.appointment', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='help_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.helptype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='infosys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.infosys'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='org_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.orguser'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.problem'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tstatus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.user'),
        ),
    ]
