# Generated by Django 4.0.6 on 2022-09-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_alter_appointment_options_alter_helptype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orguser',
            options={'ordering': ['org__name', 'last_name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
